### ISSUE TITLE
[Epic] 2.1: Documentation and Tutorials

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#10]
**Epic label**: `E:2.1: Documentation and Tutorials`
**Planned start date**: 25/09/2023
**Due date**: 07/11/2023

# Summary

Provide external contributor friendly documentation to allow end-users to easily develop / integrate with CoW Protocol.

# Acceptance Criteria

- [x] Complete rewrite of the [docs site](https://docs.cow.fi).
- [x] All templates / examples are up to date and able to be easily reasoned.
- [x] Documentation processes and tools in place to support *continual documentation* efforts.

# Tasks

- [x] docs(docs): rewrite docs site
- [x] chore(docs): implement docusaurus
- [x] chore(cow-sdk): ensure all examples current
- [x] chore(pm): review open issues for documentation
