### ISSUE TITLE
[Epic] 3.1: Driver Colocation Mainnet Production

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#14]
**Epic label**: `E:3.1 Driver Colocation`
**Planned start date**: NOW
**Due date**: 12/11/2023

# Summary

We've talked so much about it, probably not worth summarizing this EPIC (link to documentation once done)

# Acceptance Criteria

Solvers are running via the new infrastructure (one pod per solver, communicating via a dedicated driver instance with the competition being orchestrated by the autopilot) on all networks in production.

# Non code-related Tasks

- [ ] Make sure solver reward payout scripts work as expected
- [ ] Compare Pulumi config 1 by 1

## Remaining Cleanup

- [x] https://github.com/cowprotocol/services/issues/1673
- [ ] Delete Cleanup
- [ ] Fetch 0x Limit Order liquidity to driver
