### ISSUE TITLE
[Epic] 3.4: Self-documenting Rest APIs

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#23]
**Epic label**: `E:3.4 Self-documenting Rest APIs`
**Planned start date**: 01/12/2023
**Due date**: 31/12/2023

# Summary

Within the `services` repository, there are two Rest APIs that are exported in `openapi.yml`, notably in the [`orderbook`](https://github.com/cowprotocol/services/tree/6b8ac2489d6ab9104e2d28fd36358103084333c8/crates/orderbook) and the [`solvers`](https://github.com/cowprotocol/services/tree/6b8ac2489d6ab9104e2d28fd36358103084333c8/crates/solvers) crates.

When analysing these Rest APIs, it was identified that:

1. The `openapi.yml` that is used by downstream consumers is not programmatically bound / generated via CI/CD, leading to error-prone manual maintenance / updating.
2. The `solvers` crate makes use of `axum` / `tower`, as opposed to the `orderbook` crate that makes use of `warp`.

# Acceptance Criteria

On completion of this refactor, the Rest APIs shall:

1. Absent a compelling argument against, use the same dependency for running the Rest API.
2. Have their OpenAPI specification programmatically generated.
3. Have their generated OpenAPI specification thoroughly tested against the respective service for completeness / accuracy.

# Tasks

- [ ] research: [axum](https://crates.io/crates/axum) vs [warp](https://crates.io/crates/warp) (unify, or not?)
- [ ] research: suitability of [utoipa](https://crates.io/crates/utoipa) for openapi generation
- [ ] research: api property testing with [schemathesis](https://github.com/schemathesis/schemathesis)
