### ISSUE TITLE
[Epic] 4.1: Quote adjustment for solvers

### ISSUE THREAD

**Issue by olgafetisova** [cowprotocol/pm#26]
**Epic label**: `E:4.1 Quote adjustment for solvers`
**Planned start date**: 01/12/2023
**Due date**: 21/12/2023

# Summary

Quote adjustment is necessary for solvers to be able to determine the quoted price at the time of the order (market order or out-of-market order) and decide whether they need to apply additional calculations on top of that.
Additionally, the task requires storing this data for analytics purposes and the frontend team.

# Tasks

- [ ] Store quotes for all orders (currently, we don’t have quotes for limit orders, which may - if placed below market, e.g. after the Milkman refactoring - be immediately filled and otherwise cause a high fee)
- [ ] Forward the quoted amount from the autopilot to the co-located drivers
- [ ] Store quotes for analytics purposes.
