### ISSUE TITLE
[Epic] 4.2: Protocol Fee Implementation

### ISSUE THREAD

**Issue by olgafetisova** [cowprotocol/pm#29]
**Epic label**: `E:...`
**Planned start date**: 08/12/2023
**Due date**: 

# Summary

This current task requires configuring drivers (or solvers - TBD) for the successful fee implementation. The quote must pass the decision whether the fee is applicable for the current order or not, then, the fixed parameters will be applied for the fee calculation after the order is executed. Finally, we need to decide how we collect the payment from the solvers (weekly with the payouts, in COW or other).

**Iteration 1:**
- The fee is applicable for out-of-market Limit orders and Twap orders.
- For Limit orders, the fee is based on charging 50% of the surplus (max 6% of the total volume or $1000)
- For TWAP orders, the fee is based on charging 50% of the positive quote deviation (max 6% of the total volume or $1000)

**Additional requirements:**
- signal solvers if they need to adjust their quote
- make sure the solution is suitable for the future fixed fee approach - the widget will require a fixed fee setup; hence, we might need to adjust this current delivery.

# Acceptance Criteria

- Allow the product team to experiment with different fee mechanisms (surplus vs volume fee, etc)
- Allow the marketing team to create “campaigns” allowing for additional or reduced fee for certain user and orders
- Allow the BD team to work with integrations to charge an extra fee (or subsidize flow)

# Tasks

Breakdown of the work

- [ ] For Limit Orders: Adjust the per-order clearing prices to incorporate the required surplus fee or positive quote deviation (e.g. if user expected 100 DAI but the solver was able to generate 110 DAI, we need to change prices so that the user receives 105 DAI and the remaining 5 DAI stays in the settlement contract)
- [ ] Offer an endpoint to differentiate between transaction fees (gas substitute) and protocol fees (quote deviation) in the explorer
- [ ] Adjust Gnosis Solver Solution
- [ ] Communicate with our current solvers about the changes they need to apply
- [ ] Store fee information for analytics purposes.
