### ISSUE TITLE
[Epic] 5.1: Standardise contracts repository

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#31]
**Epic label**: `E:5.1: Standardise contracts repository`
**Planned start date**: 2023-01-27
**Due date**: 2024-01-07

# Summary

Following on from lessons learned with the [`loot`](https://github.com/cowprotocol/loot) and [`clogs`](https://github.com/cowprotocol/clogs) repositories, establish a standard repository layout and methodology for smart contracts within CoW Protocol.

# Acceptance Criteria

Establish a concise, thorough repository standard to which all smart contract repositories will be created from, or migrated to (in the case of existing smart contract repositories).

To be accepted, this Epic must:

- [x] Have a smart contract framework in which to develop for a post-Dencun environment
- [ ] Enforce strict logical separations between contracts, and their utilities (e.g. hardhat tasks in `contracts` would be moved to another repo, with `hardhat` being deprecated)
- [ ] Formalise rigorous internal standards for review and testing
- [x] Actively favour dependency minimisation

# Tasks

- [x] chore: github specific
  - [x] chore: contracts team as admin
  - [x] chore: contracts team as CODEOWNER
  - [x] chore: `main` branch `src` `solidity` require 2x reviews
- [x] chore: devcontainer
  - [x] feat: foundry (`forge`, `anvil`, `cast`, `chisel`) (refer above)
  - [x] feat: foundry.toml for solc and `--via-ir`
- [ ] chore: ci/cd
  - [x] chore: automatic testing (fail CI/CD < 100% coverage)
  - [x] chore: check formatting
  - [ ] chore: gas profiling and gas snapshot assessment
- [ ] chore: repo documentation
  - [ ] chore: issue templates
  - [ ] chore: readme / contributing / security
- [ ] chore: npm layout
  - [ ] chore: scope packages within `npm` folder
- [ ] chore: smart contract review checklist
  - [ ] docs: compact checklist per PR
  - [ ] docs: extended checklist for epic completion
