### ISSUE TITLE
[Epic] 3.5: Kubernetify RPC nodes

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#37]
**Epic label**: `E:3.5 Kubernetify RPC nodes`
**Planned start date**: 20/02/2024
**Due date**: 11/03/2024

# Summary

As Dencun approaches, we are being forced to upgrade our RPC nodes, and this gives us the opportunity to simultaneously eliminate a raft of tech debt. This Epic facilitates the movement of all RPC nodes from the legacy AWS account to internal services running within respective Kubernetes clusters.

# Acceptance Criteria

- [x] RPC nodes in kubernetes
- [x] Comprehensive metrics monitoring of RPC nodes
- [x] Zero-downtime (HTTP JSON-RPC only, _not including *websockets*_) node upgrade methodology
- [x] SLA to be able to deploy new nodes, fully synced, within 6 hrs
- [x] A/B methodology (production and staging environments to be identical)

# Tasks

- [x] cowprotocol/infrastructure#1124
- [x] cowprotocol/infrastructure#1125
- [x] cowprotocol/infrastructure#1127
- [x] cowprotocol/infrastructure#1158
- [x] cowprotocol/infrastructure#1159
- [x] cowprotocol/infrastructure#1153
- [x] cowprotocol/infrastructure#1154
- [x] cowprotocol/infrastructure#1155
- [x] cowprotocol/infrastructure#1152
- [x] cowprotocol/infrastructure#1202
- [x] cowprotocol/infrastructure#1199
- [x] cowprotocol/infrastructure#1203
- [x] cowprotocol/infrastructure#1208
- [x] cowprotocol/infrastructure#1204
- [x] cowprotocol/infrastructure#1156
- [x] cowprotocol/infrastructure#1207
- [x] cowprotocol/infrastructure#1380
