### ISSUE TITLE
[Epic] 4.3: Gnosis chain validators

### ISSUE THREAD

**Issue by ahhda** [cowprotocol/pm#62]
**Epic label**: `E:4.3 Gnosis chain validators`
**Planned start date**: 06/05/2024
**Due date**: 06/06/2024

# Summary

We have around 12000 idle GNO in the Treasury. A CIP was passed recently which allows the Core Team to run Gnosis Chain validators with the idle GNO. This will generate additional revenue for CoW and also help the Gnosis ecosystem.

We have around 6709 GNO in the [GC treasury](https://gnosisscan.io/address/0x616de58c011f8736fa20c7ae5352f7f6fb9f0669) and rest are locked in stakewise + in a pool of GNO-CoW. More info is in the [Karpatkey report](https://reports.karpatkey.com/?dao=5&month=3&year=2024&currency=USD).

# Acceptance Criteria

* Gnosis Chain validators are running and attesting blocks with >90% attestation rate
* IaC to launch and setup more nodes
* Slashing protection via tools like [Web3Signer](https://github.com/Consensys/web3signer)
* Monitoring/alerts for when nodes go down

# Tasks

- [x] research: cloud pricing, hardware choice, client choice
- [x] research: Finance and accounting structure (rewards address, signing etc.)
- [x] Setting up the first server and accessing bandwidth/peak CPU consumption
- [x] Ansible playbook for setting up the server
- [x] Access to servers for team members and documentation on how to manage the node
- [x] Monitoring, observability and alerts

### Choice of hardware

We would be running the validators on OVHcloud which gives us baremetal servers at a good rate ($100-$200/mo) and unlimited bandwidth.

```
Advance-1 Gen 2
Intel Xeon-E 2386G - 6c/12t - 3.5 GHz/4.7 GHz
64 GB ECC 3200 MHz
2×960 GB SSD NVMe
1 Gbit/s unmetered bandwidth
```

### Software and validator clients

* Ubuntu Server 24.04
* Docker
* Consensus client - Nimbus 
* Execution client - Erigon (pruned)
* Web3Signer (requires Postgres)
* Prometheus pushgateway
* Ansible playbooks for configuration management
