### ISSUE TITLE
[Epic] 8.1: Arbitrum One Deployment

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/pm#63]
**Epic label**: `E:8.1 Arbitrum One Deployment`
**Planned start date**: 22.04.2024
**Due date**: 31.05.2024

## TODO
polish and turn individual tasks into more detailed issues in the respective repos
also reach out to other teams to get more information about their tasks

# Summary
CoW Protocol will be deployed on **Arbitrum One**.

# Acceptance Criteria
* prod/staging backend infra continuously running for Arbitrum One
* frontend comptible with Arbitrum One is deployed for prod/staging
* nodes are hosted by us and we at most use external node providers as a back up
* all relevant contracts have been deployed, verified and permissions correctly configured
* monitoring set up (grafana + alerts)

# Tasks

## Backend @cowprotocol/backend 
- [x] prepare main pulumi stack
- [x] prepare refunder
- [x] prepare etherbalance
- [x] ensure that deployment runs stable
- [x] if necessary set up new API keys for external services (e.g. 1Inch, zeroex, etc.)

## Devops @cowprotocol/devops 
- [x] set up arbitrum nitro on top of reth nodes
- [x] set up DB (admin and read-only accounts for `arbitrum-one` on prod and staging)
- [ ] host subgraphs for balancerV2 and uniswapV3

## Frontend @cowprotocol/frontend 
- [x] publish npm module `@cowprotocol/cow-sdk` with arbitrum support
- [ ] ~deploy cow protocol [subgraph](https://github.com/cowprotocol/subgraph)?~
- [x] update CoW Swap
- [x] update Explorer
- [x] update Token list
- [x] update Watch tower

## Smart Contracts @cowprotocol/contracts 
- [x] deploy and verify contracts
- [ ] open balancer DAO vote on giving the vault relayer the required permissions
- [x] configure correct ownership for authenticator contract

## Analytics @cowprotocol/analytics 
- [x] build relevant dashboards for Arbitrum
- [ ] make sure relevant data gets uploaded to dune

## Finance @cowprotocol/finance 
- [x] ensure that accounting works on Arbitrum

## Marketing @cowmarketing @gogonimago @marshymarsh 
- [ ] tweet or other form of outreach for the launch
