### ISSUE TITLE
[Epic] 5.2: Contract migrations

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#76]
**Epic label**: `E:5.2 Contract Migrations`
**Planned start date**: 2024-01-14
**Due date**: 2024-03-31

# Summary

Migrate all existing smart contract repositories to a `core` / `periphery` / `governance` logical separation of concerns. 

# Acceptance Criteria

Upon completion of this Epic, the following must be satisfied:

- [ ] All smart contract repositories follow the standards defined by cowprotocol/pm#31 
- [ ] No extraneous smart contract repositories
- [ ] NPM packages and dependencies updated

# Tasks

- [ ] chore: forgify `contracts`
  - [x] cowprotocol/contracts#98
  - [x] cowprotocol/contracts#99
  - [x] cowprotocol/contracts#100
  - [x] cowprotocol/contracts#101
  - [x] cowprotocol/contracts#102
  - [x] cowprotocol/contracts#103
  - [ ] cowprotocol/contracts#104
  - [x] cowprotocol/contracts#105
  - [ ] cowprotocol/contracts#106
  - [ ] cowprotocol/contracts#107
  - [x] cowprotocol/contracts#108
- [ ] chore(core): migrate bench to alloy + anvil
- [ ] chore: configure `contracts-periphery` repository
- [ ] chore: migrate rest of contracts to `contracts-periphery`
  - [ ] chore: migrate `HooksTrampoline`
  - [ ] chore: migrate `ComposableCoW`
  - [ ] chore: apply test harness from `contracts-core`
  - [ ] chore: publish npm packages
