### ISSUE TITLE
[Epic] 1.2: Watch Tower Service

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/pm#8]
**Epic label**: `E:1.2: Watch Tower Service`
**Planned start date**: NOW
**Due date**: 31/10/2023

# Summary

Provide a stable, usable watch tower that is able to monitor and execute on conditional orders that are created with the `ComposableCoW` conditional order framework. 

# Acceptance Criteria

- [x] Orders are posted to the API when they are meant to be.
- [x] No requirement to run additional watch towers to catch orders missed by other watch towers.

# Tasks

- [x] https://github.com/cowprotocol/tenderly-watch-tower/issues/34
